---
info:
  title: R7insight Php
  description: PHP logging support for InsightOps
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/r7insight_php
  x-cortex-tag: r7insight-php
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: insightidr
openapi: 3.0.1
servers:
- url: "/"
